# create folder structure
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/cacerts
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/signcerts
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/user
cp ../crypto-config/peerOrganizations/global.example.com/users/Admin@global.example.com/msp/config.yaml ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/
cp ../crypto-config/peerOrganizations/global.example.com/ca/ca.global.example.com-cert.pem ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/cacerts/ca.global.example.com-cert.pem
# generate private key
openssl ecparam -name secp256r1 -genkey -noout -out ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore/priv_sk
openssl req -new -key ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore/priv_sk -out ../openssl_stuff/fakeadmincert.csr -subj "/C=US/ST=North Carolina/L=San Francisco/OU=client/CN=$1@global.example.com"
openssl x509 -req -in ../openssl_stuff/fakeadmincert.csr -CA ../openssl_stuff/fakerootcert.pem -CAkey ../openssl_perm/privkey_root.pem -CAcreateserial -out ../openssl_stuff/fakeadmincert.pem -days 500 -sha256
cd ../../bin
python3 gen_cert.py ../semproj_net/openssl_stuff/fakeadmincert.pem
cd ../semproj_net/scripts
# generate input file for signer
cat ../../bin/signer/id-10001-input_base.yaml ../../bin/signer/msg > ../../bin/signer/id-10001-input.yaml
cat ../../bin/signer/id-10002-input_base.yaml ../../bin/signer/msg > ../../bin/signer/id-10002-input.yaml
cat ../../bin/signer/id-10003-input_base.yaml ../../bin/signer/msg > ../../bin/signer/id-10003-input.yaml
cat ../../bin/signer/id-10004-input_base.yaml ../../bin/signer/msg > ../../bin/signer/id-10004-input.yaml
cat ../../bin/signer/id-10005-input_base.yaml ../../bin/signer/msg > ../../bin/signer/id-10005-input.yaml
cd ../../bin
# sign message
./alice signer --config signer/id-10001-input.yaml &
sleep 1
./alice signer --config signer/id-10002-input.yaml &
sleep 1
./alice signer --config signer/id-10003-input.yaml
cd ../semproj_net/scripts
# parse signature generated by alice
cat ../../bin/signer/id-10001-output.yaml | grep -o "[0-9]*" > ../../bin/signer/signature
# replace signature in root certificate
cd ../../bin/
python3 sign_cert.py ../semproj_net/openssl_stuff/fakeadmincert.pem signer/signature
cd ../semproj_net/scripts
# convert certificate from der to pem
openssl x509 -inform der -in ../openssl_stuff/new_cert.der -out ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/signcerts/$1@global.example.com-cert.pem