#!/bin/bash

# create folder structure
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/cacerts
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/signcerts
mkdir -p ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/user
# copy config file and root certificate
cp ../crypto-config/peerOrganizations/global.example.com/users/Admin@global.example.com/msp/config.yaml ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/
cp ../crypto-config/peerOrganizations/global.example.com/ca/ca.global.example.com-cert.pem ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/cacerts/ca.global.example.com-cert.pem

cd ../../bin
echo -e "\nGenerate private key:"

openssl ecparam -name secp256r1 -genkey -noout -out ../semproj_net/crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore/priv_sk

echo -e "\n\ncreates the csr:"

openssl req -new -key ../semproj_net/crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/keystore/priv_sk -out ../semproj_net/openssl_stuff/fakeadmincert.csr -subj "/C=US/ST=North Carolina/L=San Francisco/OU=client/CN=$1@global.example.com"

echo -e "\n\nsign csr with fake root certificate:"

openssl x509 -req -in ../semproj_net/openssl_stuff/fakeadmincert.csr -CA ../semproj_net/openssl_stuff/fakerootcert.pem -CAkey ../semproj_net/openssl_perm/privkey_root.pem -CAcreateserial -out ../semproj_net/openssl_stuff/fakeadmincert.pem -days 500 -sha256

echo -e "\n\nextract tbs and create message for alice to sign:"

python3 gen_cert.py ../semproj_net/openssl_stuff/fakeadmincert.pem


echo -e "\n\nGenerated fake user certificate:\n"
openssl x509 -in ../semproj_net/openssl_stuff/fakeadmincert.pem -text

# generate input file for signer
cat signer/id-10001-input_base.yaml signer/msg > signer/id-10001-input.yaml
cat signer/id-10002-input_base.yaml signer/msg > signer/id-10002-input.yaml
cat signer/id-10003-input_base.yaml signer/msg > signer/id-10003-input.yaml
cat signer/id-10004-input_base.yaml signer/msg > signer/id-10004-input.yaml
cat signer/id-10005-input_base.yaml signer/msg > signer/id-10005-input.yaml

# sign message

./alice signer --config signer/id-10001-input.yaml 2>&1 > /dev/null &

sleep 1

./alice signer --config signer/id-10002-input.yaml 2>&1 > /dev/null &

sleep 1

./alice signer --config signer/id-10003-input.yaml 2>&1 > /dev/null


sleep 1

# parse signature generated by alice
cat signer/id-10001-output.yaml | grep -o "[0-9]*" > signer/signature
# replace signature in root certificate
echo -e "\n\n signature substitution:\n"

python3 sign_cert.py ../semproj_net/openssl_stuff/fakeadmincert.pem signer/signature


cd ../semproj_net/scripts

# convert certificate from der to pem
echo -e "\n\nconvert certificate from der to pem:"

openssl x509 -inform der -in ../openssl_stuff/new_cert.der -out ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/signcerts/$1@global.example.com-cert.pem


echo -e "\n\nResigned user certificate:\n"
openssl x509 -in ../crypto-config/peerOrganizations/global.example.com/users/$1@global.example.com/msp/signcerts/$1@global.example.com-cert.pem -text

echo "User $1 successfully added to the blockchain"
